# Generated by Django 5.2.7 on 2026-02-26 12:00

from django.db import migrations


def create_groups(apps, schema_editor):
    """Crea los grupos predeterminados."""
    Group = apps.get_model("auth", "Group")
    group_names = ["Mesero", "Encargado", "Admin"]
    for name in group_names:
        Group.objects.get_or_create(name=name)


def reverse_groups(apps, schema_editor):
    """Elimina los grupos predeterminados (opcional)."""
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["Mesero", "Encargado", "Admin"]).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # No dependencies on other migrations within this app
    ]

    operations = [
        migrations.RunPython(create_groups, reverse_groups),
    ]