# Generated by Django 5.2.7 on 2025-11-20 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_ingredientusage_ingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='dispatch_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.dispatcharea'),
        ),
    ]
