# Generated by Django 5.2.7 on 2026-02-26 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_warehouse_ingredient_warehouse"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productingredient",
            options={"verbose_name": "Receta", "verbose_name_plural": "Recetas"},
        ),
        migrations.AlterUniqueTogether(
            name="productingredient",
            unique_together={("product", "ingredient")},
        ),
    ]
